OnlineShop.WebUI/Controllers/CartController.cs
using OnlineShop.Domain.Abstract;
using OnlineShop.Domain.Entities;
using OnlineShop.WebUI.Models;
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace OnlineShop.WebUI.Controllers
{
    public class CartController : Controller
    {
        private readonly IProductRepository _repository;
        private readonly IOrderProcessor _orderProcessor;


        public CartController(IProductRepository repo, IOrderProcessor proc)
        {
            _repository = repo;
            _orderProcessor = proc;
        }
        [AllowAnonymous]
        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                ReturnUrl = returnUrl,
                Cart = cart
            });
        }
        [AllowAnonymous]
        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
        {
            Product product = _repository.Products.FirstOrDefault(p => p.ProductId == productId);

            if (product != null)
            {
                cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        [AllowAnonymous]
        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            Product product = _repository.Products.FirstOrDefault(p => p.ProductId == productId);

            if (product != null)
            {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        [AllowAnonymous]
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }
        [AllowAnonymous]
        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }
        [AllowAnonymous]
        public ViewResult Choice()
        {
            return View(new ShippingDetails());
        }
        [AllowAnonymous]
        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (!cart.Lines.Any())
            {
                ModelState.AddModelError("", "Koszyk jest pusty!");
            }
            if (ModelState.IsValid)
            {
                _orderProcessor.ProcessOrder(cart, shippingDetails, null);
                cart.Clear();
                return View("Completed");
            }
            return View(shippingDetails);
        }

        [Authorize(Roles = "Administrator,User")]
        public ViewResult CheckoutLogin()
        {
            var userId = User.Identity.GetUserId();
            Address address = ApplicationUserManager.GetAddressByUserId(userId);
            string name = ApplicationUserManager.GetName(userId);

            var shippingDetails = new ShippingDetails()
            {
                Name = name,
                City = address.City,
                Country = address.Country,
                Line1 = address.Line1,
                Line2 = address.Line2,
                Line3 = address.Line3,
                State = address.State,
                Zip = address.Zip
            };
            
            return View("Checkout", shippingDetails);
        }

        [Authorize(Roles="Administrator,User")]
        [HttpPost]
        public ViewResult CheckoutLogin(Cart cart, ShippingDetails shippingDetails)
        {
            var userId = User.Identity.GetUserId();
            if (!cart.Lines.Any())
            {
                ModelState.AddModelError("", "Koszyk jest pusty!");
            }
            if (ModelState.IsValid)
            {
                _orderProcessor.ProcessOrder(cart, shippingDetails, userId);
                cart.Clear();
                return View("Completed");
            }
            return View("Checkout", shippingDetails);
        }
    }
}

OnlineShop.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineShop.Domain.Abstract;
using OnlineShop.Domain.Entities;
using OnlineShop.WebUI.Helpers;
using OnlineShop.WebUI.Models;

namespace OnlineShop.WebUI.Controllers
{
    [AllowAnonymous]
    public class NavController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;

        public NavController(ICategoryRepository categoryRepo)
        {
            _categoryRepository = categoryRepo;
        }
        
        public PartialViewResult Menu(string category, SortingType sortingOption = 0)
        {
            ViewBag.SelectedCategory = category;
            ViewBag.SelectedSortingOption = sortingOption;

            var menuViewModel = new MenuViewModel
            {
                Categories = _categoryRepository.Categories,
                SortingOptions = Enum.GetValues(typeof(SortingType)).Cast<SortingType>()
            };


            return PartialView("FlexMenu", menuViewModel);
        }


    }
}

OnlineShop.WebUI/Views/Shared/ProductSummary.cshtml
@using OnlineShop.WebUI.Helpers
@model OnlineShop.Domain.Entities.Product

<div class="product-box">
    @if (Model.ImageData != null)
    {
    <div class="img-product">
        <a href="@Url.RouteUrl("", new { controller = "Product", action = "Product", productId = Model.ProductId, productName = SEOHelper.EscapeUrl(Model.Name) })">
            <img class="img-thumbnail" src="@Url.Action("GetImageThumbnail", "Product", new { Model.ProductId })" />
        </a>
    </div>


    }

    <h4 class="product text-center">
        @Html.RouteLink(Model.Name, new { controller = "Product", action = "Product", productId = Model.ProductId, productName = SEOHelper.EscapeUrl(Model.Name) })

    </h4>
    <h4 class="pull-right">@Model.Price.ToString("c")</h4>
</div>

OnlineShop.WebUI/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <link href="~/Content/admin.css" rel="stylesheet" />
    <title>Sklep online CŁ - Admin</title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }

            <div class="nav">
                <div class="navbar">
                    <ul>
                        <li><a href="/Admin/Products">Produkty</a></li>
                        <li><a href="/Admin/Categories">Kategorie</a></li>
                    </ul>
                </div>
            </div>


        @RenderBody()
    </div>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
</body>
</html>

OnlineShop.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <link href="~/Content/main.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar navbar-custom" role="navigation">
        <a class="navbar-brand" href="/">
            <img class="visible-lg" src="~/Content/Images/Logo.png">
            <img class="visible-md visible-sm" src="~/Content/Images/LogoMd.png">
            <img class="visible-xs" src="~/Content/Images/LogoMobile.png">
        </a>

        @Html.Action("Summary", "Cart")
        @Html.Partial("_LoginPartial")
    </div>
<div class="row panel container-fluid" style="padding-right: 0; margin-right: 0;">
    <div class="col-sm-3 visible-lg">
        @Html.Action("Menu", "Nav")
    </div>
    <div class="col-xs-12 col-sm-8 col-md-8">
        @RenderBody()
    </div>
</div>

<div class="iframe-container">
    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d9770.748758838785!2d20.9893859!3d52.2490652!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x9e084209594a5b38!2sWarszawska+Wy%C5%BCsza+Szko%C5%82a+Informatyki!5e0!3m2!1spl!2spl!4v1547914130397" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>

    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h1>Kontakt</h1>
                <hr class="star-light">
                <form method="post" action="contact.php" class="form-horizontal">
                    <fieldset>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 col-sm-4 col-xs-12 control-label" for="topic">Temat</label>  
                            <div class="col-md-4 col-md-offset-0 col-sm-4 col-sm-offset-0 col-xs-10 col-xs-offset-1">
                                <input id="topic" name="topic" type="text" placeholder="Wpisz temat" class="form-control input-md" required>
                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 col-sm-4 col-xs-12 control-label" for="e-mail">E-mail</label>  
                            <div class="col-md-4 col-md-offset-0 col-sm-4 col-sm-offset-0 col-xs-10 col-xs-offset-1">
                                <input id="e-mail" name="e-mail" type="text" placeholder="Wpisz e-mail kontaktowy" class="form-control input-md" required>
                            </div>
                        </div>

                        <!-- Textarea -->
                        <div class="form-group">
                            <label class="col-md-4 col-sm-4 col-xs-12 control-label" for="message">Wiadomość</label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <textarea rows="10" class="form-control" id="message" name="message" placeholder="Wpisz wiadomość" required></textarea>
                            </div>
                        </div>
                        <!-- Button -->
                        <div class="form-group">
                            <label class="col-md-3 control-label" for="submit"></label>
                            <div class="col-md-3">
                                <button id="submit2" name="submit" class="btn btn-success">Wyślij</button>
                            </div>
                        </div>

                    </fieldset>
                </form>
            </div>
        </div>
    </div>

<script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/JavaScript.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>