OnlineShop.WebUI/Controllers/AdminController.cs
using System.Drawing;
using OnlineShop.Domain.Abstract;
using OnlineShop.Domain.Entities;
using OnlineShop.WebUI.Helpers;
using OnlineShop.WebUI.Models;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.WebUI.Controllers
{
    
    [Authorize(Roles = "Administrator")]
    public class AdminController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;

        public AdminController(IProductRepository repo, ICategoryRepository categoryRepo)
        {
            _productRepository = repo;
            _categoryRepository = categoryRepo;
        }

        public ViewResult Index()
        {
            
            return View();
        }

        #region Product
        public ViewResult Products()
        {
            var products = _productRepository.Products.Where(x => x.IsDeleted == false);
            if (_categoryRepository != null)
            {
                foreach (var product in products)
                {
                    product.Category =
                        _categoryRepository.Categories.FirstOrDefault(x => x.CategoryId == product.CategoryId);
                }
            }

            return View(products);
        }
        public ViewResult Create()
        {
            return View("Edit", new Product());
        }

        public ViewResult Edit(int productId)
        {
            Product product = _productRepository.Products.FirstOrDefault(p => p.ProductId == productId);
            return View(product);
        }

        [HttpPost]
        public ActionResult Edit(Product product, HttpPostedFileBase image = null)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    product.ImageMimeType = image.ContentType;
                    product.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(product.ImageData, 0, image.ContentLength);
                    product.ImageDataThumbnail = ImageHelper.CreateThumbnail(Image.FromStream(image.InputStream, true, true), 200, 200);
                }
                
                _productRepository.SaveProduct(product);
                TempData["message"] = string.Format($"Zapisano {product.Name} ");
                return RedirectToAction("Index");
            }
            else
            {
                return View(product);
            }
        }


        [HttpPost]
        public ActionResult Delete(int productId)
        {
            Product deletedProduct = _productRepository.DeleteProduct(productId);
            if (deletedProduct != null)
            {
                TempData["message"] = string.Format($"Usunięto {deletedProduct.Name}");
            }
            return RedirectToAction("Index");
        }
        #endregion  

        #region Category

        public ViewResult EditCategory(int categoryId)
        {
            Category category = _categoryRepository.Categories.FirstOrDefault(x => x.CategoryId == categoryId);
            return View(category);
        }
        [HttpPost]
        public ActionResult EditCategory(Category category)
        {
            if (ModelState.IsValid)
            {
                _categoryRepository.SaveCategory(category);
                TempData["message"] = string.Format($"Zapisano {category.CategoryName} ");
                return RedirectToAction("Index");
            }
            else
            {
                return View(category);
            }
        }

        public ViewResult Categories()
        {
            return View(_categoryRepository.Categories);
        }

        public ViewResult CreateCategory()
        {
            return View("EditCategory", new Category());
        }

        [HttpPost]
        public ActionResult DeleteCategory(int categoryId)
        {
            Category deletedCategory = _categoryRepository.DeleteCategory(categoryId);
            if (deletedCategory != null)
            {
                TempData["message"] = string.Format($"Usunięto {deletedCategory.CategoryName}");
            }
            return RedirectToAction("Index");
        }

        [ChildActionOnly]
        public ActionResult DropDownList()
        {
            var categories = _categoryRepository.Categories.Distinct();
            var viewmodel = new CategoryViewModel
            {
                Categories = new SelectList(categories, "CategoryId", "CategoryName")
            };

            return PartialView(viewmodel);
        }
        #endregion



    }
}

OnlineShop.WebUI/Controllers/ProductController.cs
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System;
using System.Web.Mvc;
using OnlineShop.Domain.Abstract;
using OnlineShop.Domain.Entities;
using OnlineShop.WebUI.Models;

namespace OnlineShop.WebUI.Controllers
{
    [AllowAnonymous]
    public class ProductController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;
        public int PageSize = 16;

        public ProductController(IProductRepository productRepository, ICategoryRepository categoryRepo)
        {
            _productRepository = productRepository;
            _categoryRepository = categoryRepo;
        }


        public ViewResult List(string category, int page = 1, SortingType sortingOption = 0)
        {
            int categoryId = 0;
            if (_categoryRepository != null)
            {
                categoryId = _categoryRepository.GetCategoryId(category);
            }

            IEnumerable<Product> products = _productRepository.Products.Where(x => x.IsDeleted == false).OrderBy(x => x.ProductId);

            switch (sortingOption)
            {
                case SortingType.NoSorting:
                    break;
                case SortingType.NameAZ:
                    products = products.OrderBy(x => x.Name);
                    break;
                case SortingType.NameZA:
                    products = products.OrderByDescending(x => x.Name);
                    break;
                case SortingType.HighestPrice:
                    products = products.OrderByDescending(x => x.Price);
                        break;
                case SortingType.LowestPrice:
                    products = products.OrderBy(x => x.Price);
                    break;
                case SortingType.MostPopular:
                    products = products.OrderByDescending(x => x.NumberOfBought).ThenByDescending(x => x.Visits);
                    break;
            }

            if (page == 1)
                products = products.Where(x => category == null || x.CategoryId == categoryId).Take(PageSize);
            else
                products = products.Where(x => category == null || x.CategoryId == categoryId).Skip((page - 1) * PageSize);

            var model = new ProductsListViewModel
            {
                Products = products,
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ? _productRepository.Products.Count() 
                        : _productRepository.Products.Count(e => e.CategoryId == categoryId)
                },
                CurrentCategory = category,
                CurrentSorting = sortingOption
            };
            return View(model);
        }

        public FileContentResult GetImage(int productId)
        {
            var prod = _productRepository.Products.FirstOrDefault(p => p.ProductId == productId);
            return prod != null ? File(prod.ImageData, prod.ImageMimeType) : null;
        }
        public FileContentResult GetImageThumbnail(int productId)
        {
            var prod = _productRepository.Products.First(p => p.ProductId == productId);
            if (prod?.ImageDataThumbnail == null)
            {
                return GetImage(productId);
            }
            return prod != null ? File(prod.ImageDataThumbnail, prod.ImageMimeType) : null;
        }

        public ActionResult Product(int productId)
        {
            var product = _productRepository.Products.FirstOrDefault(x => x.ProductId == productId);
            product.Category = _categoryRepository.Categories.FirstOrDefault(x => x.CategoryId == product.CategoryId);

            var visited = Convert.ToBoolean(System.Web.HttpContext.Current.Session["VisitedId: " + productId]);
            if (!visited)
            {
                System.Web.HttpContext.Current.Session["VisitedId: " + productId] = true;
                product.Visits++;
                _productRepository.SaveProduct(product);
            }
            return View(product);
        }
    }
}

OnlineShop.WebUI/Views/Admin/Categories.cshtml
@model IEnumerable<OnlineShop.Domain.Entities.Category>
@{
    ViewBag.Title = "Admin: Kategorie";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container panel panel-default">
    <div class="">
        <h3>Kategorie</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-right">Id</th>
                <th>Nazwa</th>
                <th>Akcje</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-right">@item.CategoryId</td>
                    <td>@Html.ActionLink(item.CategoryName, "EditCategory", new { item.CategoryId })</td>
                    <td class="text-center">
                        @using (Html.BeginForm("DeleteCategory", "Admin"))
                        {
                            @Html.Hidden("CategoryId", item.CategoryId)
                            <input type="submit"
                                   class="btn btn-default btn-xs"
                                   value="Usuń" />
                        }
                    </td>
                </tr>
            }
        </table>
    </div>
    <div style="margin-bottom: 10px;">
        @Html.ActionLink("Dodaj nową kategorię", "CreateCategory", null,
        new { @class = "btn btn-default" })
    </div>
</div>

OnlineShop.WebUI/Views/Admin/DropDownList.cshtml
@model OnlineShop.WebUI.Models.CategoryViewModel


@Html.DropDownListFor(m => m.CategoryId, Model.Categories, "-- Wybierz kategorię --", new { @id = "Category", @name = "Category", @class = "form-control" })

OnlineShop.WebUI/Views/Admin/Edit.cshtml
@model OnlineShop.Domain.Entities.Product
@{
    ViewBag.Title = "Admin: Edycja " + @Model.Name;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container panel">
    <div class="panel-heading">
        <h3>Edycja @Model.Name</h3>
    </div>
    @using (Html.BeginForm("Edit", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="panel-body">
            @Html.HiddenFor(m => m.ProductId)
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                switch (property.PropertyName)
                {
                    case "ProductId":
                    case "ImageData":
                    case "ImageMimeType":
                    case "Visits":
                    case "NumberOfBought":
                    case "NumberOfComments":
                    case "CategoryId":
                    case "ImageDataThumbnail":
                    case "IsDeleted":
                        break;
                    default:


            <div class="form-group">
                <label>@(property.DisplayName ?? property.PropertyName)</label>
                @if (property.PropertyName == "Description")
                {
                    @Html.TextArea(property.PropertyName, null,
                    new { @class = "form-control", rows = 5 })
                }
                else if (property.PropertyName == "Category")
                {
                    @Html.Action("DropDownList", "Admin")
                }
                else
                {
                    @Html.TextBox(property.PropertyName, null,
                    new { @class = "form-control" })
                }
                @Html.ValidationMessage(property.PropertyName)
            </div>
                        break;
                }
            }
            <div class="form-group" style="">
                <div style="position: relative;">
                    <label>Zdjęcie</label>
                    <a style="position: relative;" class='btn btn-default' href='javascript:;'>
                        Wybierz plik...
                        <input type="file" name="Image" style="position:absolute; width: 113px; height: 34px; top:0; left:0; filter: alpha(opacity=0);opacity:0;
                                                                          background-color:transparent; color:transparent;" onchange='$("#upload-file-info").html($(this).val());'>
                    </a>
                    <span class='label label-info' id="upload-file-info"></span>
                </div>
                @if (Model.ImageData == null)
                {
                    <div class="form-control-static" style="margin-top: 10px;">Brak zdjęcia</div>
                }
                else
                {
                    <img class="img-thumbnail" width="150" height="150" style="margin-top: 10px;" src="@Url.Action("GetImage", "Product", new { Model.ProductId })" />
                }
            </div>
        </div>


        <div class="panel-footer">
            <input type="submit" value="Zapisz" class="btn btn-primary" />
            @Html.ActionLink("Anuluj i wróć do listy", "Index", null, new {
            @class = "btn btn-default"
            })
        </div>
    }
</div>

OnlineShop.WebUI/Views/Admin/EditCategory.cshtml
@using System.Web.Razor.Generator
@model OnlineShop.Domain.Entities.Category
@{
    ViewBag.Title = "Admin: Edycja " + @Model.CategoryName;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container panel">
    <div class="panel-heading">
        <h3>Edycja @Model.CategoryName</h3>
    </div>
    @using (Html.BeginForm("EditCategory", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="panel-body">
            @Html.HiddenFor(m => m.CategoryId)
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                switch (property.PropertyName)
                {
                    case "CategoryId": 
                        break;
                    default:
                        <div class="form-group">
                            <label>@(property.DisplayName ?? property.PropertyName)</label>
                                @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
                            @Html.ValidationMessage(property.PropertyName)
                        </div>
                        break;
                }
            }
        </div>
        

        <div class="panel-footer">
            <input type="submit" value="Zapisz" class="btn btn-primary" />
            @Html.ActionLink("Anuluj i wróć do listy", "Index", null, new {
            @class = "btn btn-default"
            })
        </div>
    }
</div>

OnlineShop.WebUI/Views/Admin/Index.cshtml
@model IEnumerable<OnlineShop.Domain.Entities.Product>
@{
    ViewBag.Title = "Admin: Wszystkie produkty";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

OnlineShop.WebUI/Views/Admin/Products.cshtml
@model IEnumerable<OnlineShop.Domain.Entities.Product>
@{
    ViewBag.Title = "Admin: Wszystkie produkty";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container panel panel-default">
    <div class="">
        <h3>Wszystkie produkty</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-right">Id</th>
                <th>Nazwa</th>
                <th class="text-right">Cena</th>
                <th class="text-center">Akcje</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-right">@item.ProductId</td>
                    <td>@Html.ActionLink(item.Name, "Edit", new { item.ProductId })</td>
                    <td class="text-right">@item.Price.ToString("c")</td>
                    <td class="text-center">
                        @using (Html.BeginForm("Delete", "Admin"))
                        {
                            @Html.Hidden("ProductId", item.ProductId)
                            <input type="submit"
                                   class="btn btn-default btn-xs"
                                   value="Usuń" />
                        }
                    </td>
                </tr>
            }
        </table>
    </div>
    <div style="margin-bottom: 10px;">
        @Html.ActionLink("Dodaj nowy produkt", "Create", null,
        new { @class = "btn btn-default" })
    </div>
</div>